In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('movie_success_rate.csv')
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,...,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western,Success
0,1.0,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014.0,121.0,8.10000,757074.0000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,2.0,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012.0,124.0,7.00000,485820.0000,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,3.0,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016.0,117.0,7.30000,157606.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,4.0,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016.0,108.0,7.20000,60545.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.0,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016.0,123.0,6.20000,393727.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,995.0,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012.0,88.0,6.70000,164088.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
835,997.0,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007.0,94.0,5.50000,73152.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
836,998.0,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008.0,98.0,6.20000,70699.0000,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
837,1000.0,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016.0,87.0,5.30000,12435.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.81432,193230.2518,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.shape

(839, 33)

In [3]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,...,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western,Success
0,1.0,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014.0,121.0,8.1,757074.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,2.0,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012.0,124.0,7.0,485820.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,3.0,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016.0,117.0,7.3,157606.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,4.0,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016.0,108.0,7.2,60545.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.0,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016.0,123.0,6.2,393727.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Action', 'Adventure', 'Aniimation', 'Biography', 'Comedy',
       'Crime', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War',
       'Western', 'Success'],
      dtype='object')

In [5]:
df['Genre'].value_counts()

Action,Adventure,Sci-Fi       50
Comedy,Drama,Romance          30
Drama                         29
Drama,Romance                 27
Animation,Adventure,Comedy    26
                              ..
Drama,Fantasy,War              1
Drama,Fantasy,Music            1
Comedy,Family,Romance          1
Action,Adventure,Western       1
Comedy,Family,Fantasy          1
Name: Genre, Length: 189, dtype: int64

In [6]:
df['Director'].value_counts()

Ridley Scott          8
Michael Bay           6
David Yates           6
Paul W.S. Anderson    6
J.J. Abrams           5
                     ..
Xavier Dolan          1
Todd Haynes           1
Joey Curtis           1
Bryan Bertino         1
Colin Strause         1
Name: Director, Length: 524, dtype: int64

In [8]:
df['Actors'].value_counts()

Shia LaBeouf, Megan Fox, Josh Duhamel, Tyrese Gibson                   2
Gerard Butler, Aaron Eckhart, Morgan Freeman,Angela Bassett            2
Daniel Radcliffe, Emma Watson, Rupert Grint, Michael Gambon            2
Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson    2
Billy Crystal, John Goodman, Steve Buscemi, Helen Mirren               1
                                                                      ..
Dwayne Johnson, John Hurt, Ian McShane, Joseph Fiennes                 1
Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Ken Watanabe      1
Sam Worthington, Liam Neeson, Rosamund Pike, Ralph Fiennes             1
Sam Worthington, Elizabeth Banks, Jamie Bell, Mandy Gonzalez           1
Justin Chatwin, James Marsters, Yun-Fat Chow, Emmy Rossum              1
Name: Actors, Length: 834, dtype: int64

In [9]:
df= df.fillna(df.median())

In [10]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Action', 'Adventure', 'Aniimation', 'Biography', 'Comedy',
       'Crime', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War',
       'Western', 'Success'],
      dtype='object')

In [11]:
x= df[['Year','Runtime (Minutes)','Rating','Votes','Revenue (Millions)','Metascore', 'Action', 'Adventure', 'Aniimation',
      'Biography', 'Comedy','Crime', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music','Musical', 'Mystery', 
      'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War','Western']]
y=df[['Success']]

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.1,stratify=y)

In [23]:
from sklearn.metrics import confusion_matrix
clf=confusion_matrix(y_test,log.predict(x_test))

AttributeError: 'builtin_function_or_method' object has no attribute 'predict'

In [22]:
import seaborn as sns
sns.heatmap(clf,annot=True)

NameError: name 'clf' is not defined

In [24]:
corr=df.corr()
corr.style.background_gradient(cmap='magma').set_precision(2)

In [25]:
#importing the models

from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [27]:
RF=RandomForestClassifier()
RF.fit(x_train,y_train)
y_predict=RF.predict(x_test)

#Prediction summary
print(classification_report(y_test,y_predict))

#Accuracy score
RF_SC=accuracy_score(y_predict,y_test)
print(f"{round(RF_SC*100,2)}% accuracy")

<ipython-input-27-0e0e059b4ef8>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RF.fit(x_train,y_train)

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        69
         1.0       1.00      1.00      1.00        15

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84

100.0% accuracy

In [28]:
LR=LogisticRegression()
LR.fit(x_train,y_train)
y_predict=LR.predict(x_test)

#Prediction summary
print(classification_report(y_test,y_predict))

#Accuracy score
LR_SC=accuracy_score(y_predict,y_test)
print(f"{round(LR_SC*100,2)}% accuracy")

C:\shreyas\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

              precision    recall  f1-score   support

         0.0       0.92      0.99      0.95        69
         1.0       0.90      0.60      0.72        15

    accuracy                           0.92        84
   macro avg       0.91      0.79      0.84        84
weighted avg       0.92      0.92      0.91        84

91.67% accuracy

In [32]:
KNN=KNeighborsClassifier(n_neighbors=40,p=2,metric='euclidean')
KNN.fit(x_train,y_train)
y_predict=KNN.predict(x_test)

print(classification_report(y_test,y_predict))

KNN_SC=accuracy_score(y_predict,y_test)
print(f"{round(KNN_SC*100,2)}% accuracy")

C:\shreyas\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

              precision    recall  f1-score   support

         0.0       0.89      0.94      0.92        69
         1.0       0.64      0.47      0.54        15

    accuracy                           0.86        84
   macro avg       0.76      0.70      0.73        84
weighted avg       0.85      0.86      0.85        84

85.71% accuracy

In [33]:
score=[KNN_SC,RF_SC,LR_SC]
models=pd.DataFrame({
    'Algorithm Model':['K Nearest Neighbour','Random Forest','Logistic Regression'],'Score':score})
models.sort_values(by='Score',ascending=False)

       Algorithm Model     Score
1        Random Forest  1.000000
2  Logistic Regression  0.916667
0  K Nearest Neighbour  0.857143